/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd_drive;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;

/**
 *
 * @author Gregory De León
 */
public class Drive extends javax.swing.JFrame {

    public String carpetaactual="/";
    public String direccion="/";
    public Drive() {
        initComponents();        
        this.setTitle("drive "+EDD_Drive.user.usuarios[EDD_Drive.usuarioactual].usuario);
        crearbotones(carpetaactual,direccion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPcar = new javax.swing.JPanel();
        btncrearcar = new javax.swing.JButton();
        btnmodcar = new javax.swing.JButton();
        btnelicar = new javax.swing.JButton();
        btnupcar = new javax.swing.JButton();
        jParc = new javax.swing.JPanel();
        btncreararc = new javax.swing.JButton();
        btnmodarc = new javax.swing.JButton();
        btneliarc = new javax.swing.JButton();
        btnuparc = new javax.swing.JButton();
        jPcontenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPcar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Carpetas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        btncrearcar.setText("Crear");
        btncrearcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearcarActionPerformed(evt);
            }
        });

        btnmodcar.setText("Modificar");

        btnelicar.setText("Eiminar");

        btnupcar.setText("Subir");

        javax.swing.GroupLayout jPcarLayout = new javax.swing.GroupLayout(jPcar);
        jPcar.setLayout(jPcarLayout);
        jPcarLayout.setHorizontalGroup(
            jPcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncrearcar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodcar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(btnelicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnupcar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPcarLayout.setVerticalGroup(
            jPcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcarLayout.createSequentialGroup()
                .addComponent(btncrearcar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmodcar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnelicar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnupcar)
                .addContainerGap())
        );

        jParc.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Archivos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        btncreararc.setText("Crear");
        btncreararc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreararcActionPerformed(evt);
            }
        });

        btnmodarc.setText("Modificar");

        btneliarc.setText("Eiminar");

        btnuparc.setText("Subir");

        javax.swing.GroupLayout jParcLayout = new javax.swing.GroupLayout(jParc);
        jParc.setLayout(jParcLayout);
        jParcLayout.setHorizontalGroup(
            jParcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jParcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jParcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncreararc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmodarc, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(btneliarc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnuparc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jParcLayout.setVerticalGroup(
            jParcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jParcLayout.createSequentialGroup()
                .addComponent(btncreararc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnmodarc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneliarc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnuparc)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jParc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPcontenido, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPcontenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jParc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncrearcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearcarActionPerformed
        String name=JOptionPane.showInputDialog(null,"Nombre de la carpeta");
        if(name!=null){
            EDD_Drive.user.usuarios[EDD_Drive.usuarioactual].carpetas.insertar(this.carpetaactual, name);
        }
        String allarchivo = EDD_Drive.user.usuarios[EDD_Drive.usuarioactual].carpetas.BuscarArchivos(this.carpetaactual);
        crearbotones(this.carpetaactual,this.direccion);
    }//GEN-LAST:event_btncrearcarActionPerformed

    private void btncreararcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreararcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncreararcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Drive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Drive().setVisible(true);
            }
        });
    }
    
    private void crearbotones(String carpeta,String direccion){
        jPcontenido.removeAll();
        jPcontenido.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), direccion, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12)));
        javax.swing.JButton btnregresar=new javax.swing.JButton("...");
        btnregresar.addActionListener((ActionEvent e) -> 
                {
                    String[] carpetas=Arrays.asList(this.direccion.split("/")).stream().filter(str -> !str.isEmpty()).collect(Collectors.toList()).toArray(new String[0]);
                    System.out.println("numero de carpetas: "+carpetas.length);
                    System.out.println("carpetas: "+Arrays.toString(carpetas));
                    String direccionnueva="";
                    for (int i = 0; i < (carpetas.length-1); i++) {
                            direccionnueva+="/";
                            direccionnueva+=carpetas[i];        
                    }
                    System.out.println("direccion nueva: "+direccionnueva);
                    if(direccionnueva.equals("")){
                        this.direccion="/";
                        this.carpetaactual="/";
                    }else{
                        this.direccion=direccionnueva;
                        System.out.println("carpeta nueva: "+carpetas[carpetas.length-2]);
                        this.carpetaactual=carpetas[carpetas.length-2];
                    }
                    crearbotones(carpetaactual,this.direccion);
                });
        jPcontenido.add(btnregresar);
        String carp=EDD_Drive.user.usuarios[EDD_Drive.usuarioactual].carpetas.BuscarArchivos(carpeta);
        String archivos[]=carp.split(",");
        javax.swing.JButton carpetas[]=new javax.swing.JButton[archivos.length];
        for (int i=0;i<archivos.length;i++) {
            if (!archivos[i].equals("")) {
                String archivos2[]=archivos[i].split("/");
                carpetas[i]=new javax.swing.JButton(archivos2[archivos2.length-1]);
                carpetas[i].addActionListener((ActionEvent e) -> 
                {
                    System.out.println(e.getActionCommand());
                    if (this.carpetaactual.equals("/")) {
                        this.direccion+=e.getActionCommand();
                    }else{
                        this.direccion=this.direccion+"/"+e.getActionCommand();
                    }
                    this.carpetaactual=e.getActionCommand();   
                    crearbotones(carpetaactual,this.direccion);
                });
                jPcontenido.add(carpetas[i]);
            }  
        }
        jPcontenido.revalidate();
        jPcontenido.repaint(); 
    }
    
    private void eventocarpeta(java.awt.event.ActionEvent evt,String nombre) {                                            
        
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreararc;
    private javax.swing.JButton btncrearcar;
    private javax.swing.JButton btneliarc;
    private javax.swing.JButton btnelicar;
    private javax.swing.JButton btnmodarc;
    private javax.swing.JButton btnmodcar;
    private javax.swing.JButton btnuparc;
    private javax.swing.JButton btnupcar;
    private javax.swing.JPanel jParc;
    private javax.swing.JPanel jPcar;
    private javax.swing.JPanel jPcontenido;
    // End of variables declaration//GEN-END:variables
}
